# Generated by Django 4.0.2 on 2022-02-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('rasm', models.FileField(upload_to='bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Ichki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('rasm', models.FileField(upload_to='ichki')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('rasm', models.FileField(upload_to='mahsulot')),
                ('batafsil', models.TextField()),
                ('brend', models.CharField(max_length=35)),
                ('kafolaat', models.CharField(blank=True, max_length=35)),
                ('mavjud', models.BooleanField(default=True)),
                ('yetkazish', models.CharField(blank=True, max_length=20)),
                ('narx', models.PositiveIntegerField()),
                ('aksiya', models.PositiveSmallIntegerField(default=0)),
                ('ichki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ichki')),
            ],
        ),
    ]
