# Generated by Django 4.0.2 on 2022-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_mahsulot_ichki'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='mamlakat',
            field=models.CharField(default='China', max_length=45),
        ),
    ]
