# Generated by Django 4.0.2 on 2022-02-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0005_mahsulot_mamlakat'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('summa', models.PositiveIntegerField()),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tezkor', models.BooleanField(default=False)),
                ('karta_ism', models.CharField(max_length=30)),
                ('raqam', models.CharField(max_length=17)),
                ('cvv', models.CharField(max_length=3)),
                ('oy', models.PositiveSmallIntegerField()),
                ('yil', models.PositiveSmallIntegerField()),
                ('buyurtma', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyurtma.buyurtma')),
                ('manzil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.PositiveSmallIntegerField(default=1)),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.client')),
            ],
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='savat',
            field=models.ManyToManyField(to='buyurtma.Savat'),
        ),
    ]
