# Generated by Django 4.0.2 on 2022-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanlangan',
            name='son',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
