# Generated by Django 4.0.5 on 2022-06-24 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_mahsulot_mamlakat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyurtma', '0002_tanlangan_son'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotibol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karta_ism', models.CharField(default=None, max_length=30)),
                ('raqam', models.CharField(default=None, max_length=30)),
                ('cvv', models.CharField(default=None, max_length=10)),
                ('oy', models.CharField(default=None, max_length=50)),
                ('yil', models.CharField(default=None, max_length=50)),
                ('ism', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('tel', models.CharField(default=None, max_length=50)),
                ('maxsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mahsulot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
