# Generated by Django 4.0.2 on 2022-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_adress_kocha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
